name: CI
on: [push, pull_request]

jobs:
  linux-c:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Build and test
        run: .github/bin/test_asan.sh
  windows-cl:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - name: Build and test
        shell: cmd
        run: .github/bin/test_c.bat
  windows-gcc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - name: Build and test
        shell: bash
        run: .github/bin/test_c.sh
  linux-perl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup Perl
        uses: shogo82148/actions-setup-perl@v1
      - name: Install dependencies
        run: cpanm -v --notest --no-man-pages Module::Build
      - name: Build and test
        run: .github/bin/test_perl.sh
